spring:
  application:
    name: api-gateway-zuul
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:1111/eureka/
    enabled: true
zuul:
  routes:
    hello-service:
      path: /api-a/**
      serviceId: hello-service
    hello-feign-consomer:
      path: /api-b/**
      serviceId: hello-feign-consomer
    api-c:
      path: /api-c/**
      url: forward:/api-a
  ignored-services: '*'
server:
  port: 9000
management:
  endpoints:
    web:
      exposure:
        include: '*'
#zuul:
#  routes:
#    hello-service:
#      path: /api-a/**
#      serviceId: hello-service
#      url: http://localhost:8080/
#hello-service:
#  ribbon:
#    listOfServers: http://localhost:8080/,http://localhost:8081/
#logging:
#  level:
#    root: debug