spring:
  cloud:
    gateway:
      default-filters:
        - PrefixPath=/hello-service
        - AddResponseHeader=X-Response-Default-Foo, Default-Bar
      routes:
        - id: hello-service
          uri: http://localhost:8080
          predicates:
            - Path=/hello
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.loadbalancer: TRACE